version: "3.9"

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ./data:/app/data  
      - rag-store:/app/rag_store  
    depends_on:
      - ollama
  db:
    image: postgres:16
    container_name: ai_tutor_db
    restart: always
    environment:
      POSTGRES_USER: ai_tutor
      POSTGRES_PASSWORD: ai_tutor
      POSTGRES_DB: ai_tutor
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama:latest
    command: ["serve"]   # ðŸ”¥ THIS IS THE FIX
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
      
      

volumes:
  ollama-data:
  rag-store:
  postgres-data: