version: "3.9"

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://ai_tutor:ai_tutor@db:5432/ai_tutor
      - ADMIN_API_KEY=super-secret-admin-key
      - LLM_PROVIDER=ollama
      - OLLAMA_BASE_URL=http://ollama:11434
      - LLM_TIMEOUT_SECONDS=300
    volumes:
      - ./:/app
      - ./data:/app/data  
      - rag-store:/app/rag_store  
    depends_on:
      - db
      - ollama
  db:
    image: postgres:16
    
    restart: always
    environment:
      POSTGRES_USER: ai_tutor
      POSTGRES_PASSWORD: ai_tutor
      POSTGRES_DB: ai_tutor
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama:latest
    command: ["serve"]   # ðŸ”¥ THIS IS THE FIX
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
      
      

volumes:
  ollama-data:
  rag-store:
  postgres-data:
